Project 2 - Responsive Design - Milestone Two - Finish
jmontanholi/ProjectTwoMilestoneTwo pull request #1
Opened 2021-02-25 17:47 UTC by jmontanholi

# The implementations done in this Branch were:

- Categories HTML and CSS
- Latest News HTML and CSS
- Latest Deals HTML and CSS
- All three with Responsive Queries (for Mobile, Ipad, and Desktop)

2021-02-25 19:43 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @jmontanholi, @errea & @mrigorir 👋 


The codebase is greatly inspiring with how you have implemented the layout using CSS and HTML. Most of the requirements are getting met and the hard work in putting out a professionally kept repo is evident from the commit messages to the Pull Request. Keep it up.

Below, 👇 I have highlighted some few suggestions that might require your attention.

The changes touch on having to provide a live link to where the page is hosted live to getting the general layout right to finally some suggestions on some code that appear to be redundant. Take a look and tell me what you think. 

### Happy coding 💻 
#### Christianb Otieno (CR)

2021-02-25 19:43 UTC, christianotieno commented on README.md
>  ![](https://img.shields.io/badge/Microverse-blueviolet)
## Improve the live link of the page on the `README` 
- [ ] Please add a live link to where the page is hosted live. the current link appears to be broken aa it throws a `404` error.

2021-02-25 19:43 UTC, christianotieno commented on index.html
> +    <!-- Latest News -->
## Improve the `general layout` of the page
- [ ] The `general layout` of the page from top to bottom are not aligned as viewed or compared with the original page. You should note that the first main three articles must not cover the same width as that of the rest of the contents of the page. The width is much wider in this section as the rest of the section gets to be uniform, lesser and centred. Have a look at the comparison below for inspiration. 👇 
- [ ] Be mindful of the spacing around elements and the font sizes as well. they appear much bolder on the source page.

|[Source Page](https://perma.cc/M5ZV-Q2D6)|[Clone Page](https://raw.githack.com/jmontanholi/ProjectTwoMilestoneTwo/categories/index.html)|
|:--:|:--:|
|![tnw](https://user-images.githubusercontent.com/22345961/109206523-03b85800-77b9-11eb-8a40-18ad60aa574f.png)|![tnw-clone](https://user-images.githubusercontent.com/22345961/109206560-103cb080-77b9-11eb-9059-9d8c2b8d12a8.png)|

2021-02-25 19:43 UTC, christianotieno commented on queries.css
> +  }
## Aim to Stay `DRY`
- [ ] The lines of code on line `#146` & `#162` appear to be similar and make you seem like you are repeating yourself. Would you mind merging them so as to not appear redundant?

2021-02-25 19:43 UTC, christianotieno commented on queries.css
> +  }
## Thumbs up 👍 
✅ Great job showcasing the greatness that comes with arranging items on the UI using the `grid` box rule. I love how you pulled this off in a neat and minimalistic way. Awesome stuff.

2021-02-25 19:43 UTC, christianotieno commented on styles.css
> +}
## Aim to Stay `DRY`
- [ ] The lines of code on line `#628` & `#648` appear to be similar and make you seem like you are repeating yourself. Would you mind merging them so as to not appear redundant?

2021-02-26 02:58 UTC, Georjane approved these changes
## Status: PR Approved ✔️ ✔️
### Hi Team 🙌
Very nice work you have there. Congratulations on successfully completing this project. 🎊 It meets the minimum requirements for approval. 

It would be very nice to have a screenshot of your project in your Readme file too. Other than that, you can go ahead and merge this PR. 👍 

Good luck on your next project and Happy Coding 💻

2021-02-26 09:13 UTC, merged

2021-02-26 09:15 UTC, errea commented
👍Well-done @jmontanholi 🙌 we did a great job.